In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/Users/shuva/Desktop/Ml_learn/town.csv")
df

               town  area   price  Unnamed: 3
0   monroe township  2600  550000         NaN
1   monroe township  3000  565000         NaN
2   monroe township  3200  610000         NaN
3   monroe township  3600  680000         NaN
4   monroe township  4000  725000         NaN
5      west windsor  2600  585000         NaN
6      west windsor  2800  615000         NaN
7      west windsor  3300  650000         NaN
8      west windsor  3600  710000         NaN
9       robinsville  2600  575000         NaN
10      robinsville  2900  600000         NaN
11      robinsville  3100  620000         NaN
12      robinsville  3600  695000         NaN

In [3]:
df.dropna(axis =1,how ='any',inplace = True)

In [4]:
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [5]:
dumies = pd.get_dummies(df.town)
dumies

    monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [6]:
merged = pd.concat([df,dumies],axis = 1)
merged

               town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [7]:
final = merged.drop(['town','west windsor'],axis = 1)
final

    area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [8]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [9]:
X = final.drop('price',axis = 1)
X

    area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [10]:
y = final.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [11]:
model.fit(X,y)

LinearRegression()

In [12]:
model.predict([[2800,0,1]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([590775.63964739])

In [13]:
model.predict([[3400,0,0]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([681241.66845839])

In [14]:
model.score(X,y)

0.9573929037221873

## ONE HOT ENCODING

In [15]:
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [16]:
# -> 1ST. LABEL ENCODING
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [17]:

df['town_label'] = le.fit_transform(df['town'])
df

               town  area   price  town_label
0   monroe township  2600  550000           0
1   monroe township  3000  565000           0
2   monroe township  3200  610000           0
3   monroe township  3600  680000           0
4   monroe township  4000  725000           0
5      west windsor  2600  585000           2
6      west windsor  2800  615000           2
7      west windsor  3300  650000           2
8      west windsor  3600  710000           2
9       robinsville  2600  575000           1
10      robinsville  2900  600000           1
11      robinsville  3100  620000           1
12      robinsville  3600  695000           1

In [18]:
X = df[['town_label','area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [19]:
y = df['price'].values
y

array([550000, 565000, 610000, 680000, 725000, 585000, 615000, 650000,
       710000, 575000, 600000, 620000, 695000], dtype=int64)

In [20]:
# -> now apply dummies variable for one hot encoder
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first', sparse_output = False)

In [21]:
# drop town 
df = df.drop(['town'],axis =1)
df

    area   price  town_label
0   2600  550000           0
1   3000  565000           0
2   3200  610000           0
3   3600  680000           0
4   4000  725000           0
5   2600  585000           2
6   2800  615000           2
7   3300  650000           2
8   3600  710000           2
9   2600  575000           1
10  2900  600000           1
11  3100  620000           1
12  3600  695000           1

In [22]:
encoded_features =  ohe.fit_transform(df[['town_label']])

In [24]:
encoded_df = pd.DataFrame(encoded_features, columns = ohe.get_feature_names_out(['town_label']))
encoded_df

    town_label_1  town_label_2
0            0.0           0.0
1            0.0           0.0
2            0.0           0.0
3            0.0           0.0
4            0.0           0.0
5            0.0           1.0
6            0.0           1.0
7            0.0           1.0
8            0.0           1.0
9            1.0           0.0
10           1.0           0.0
11           1.0           0.0
12           1.0           0.0

In [27]:
# combine with original DataFrame
df_final = pd.concat([df.drop(columns=['town_label']),encoded_df],axis =1)
df_final

    area   price  town_label_1  town_label_2
0   2600  550000           0.0           0.0
1   3000  565000           0.0           0.0
2   3200  610000           0.0           0.0
3   3600  680000           0.0           0.0
4   4000  725000           0.0           0.0
5   2600  585000           0.0           1.0
6   2800  615000           0.0           1.0
7   3300  650000           0.0           1.0
8   3600  710000           0.0           1.0
9   2600  575000           1.0           0.0
10  2900  600000           1.0           0.0
11  3100  620000           1.0           0.0
12  3600  695000           1.0           0.0

In [30]:
X = df_final.drop(columns = ['price']).values
X

array([[2.6e+03, 0.0e+00, 0.0e+00],
       [3.0e+03, 0.0e+00, 0.0e+00],
       [3.2e+03, 0.0e+00, 0.0e+00],
       [3.6e+03, 0.0e+00, 0.0e+00],
       [4.0e+03, 0.0e+00, 0.0e+00],
       [2.6e+03, 0.0e+00, 1.0e+00],
       [2.8e+03, 0.0e+00, 1.0e+00],
       [3.3e+03, 0.0e+00, 1.0e+00],
       [3.6e+03, 0.0e+00, 1.0e+00],
       [2.6e+03, 1.0e+00, 0.0e+00],
       [2.9e+03, 1.0e+00, 0.0e+00],
       [3.1e+03, 1.0e+00, 0.0e+00],
       [3.6e+03, 1.0e+00, 0.0e+00]])

In [31]:
y= df_final.price.values
y

array([550000, 565000, 610000, 680000, 725000, 585000, 615000, 650000,
       710000, 575000, 600000, 620000, 695000], dtype=int64)

In [33]:
model.fit(X,y)

LinearRegression()

In [ ]:
model.predict([2800])